# Generated by Django 4.0.3 on 2022-04-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='TipoUsuario',
        ),
    ]
