# Generated by Django 4.0.3 on 2022-04-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GrupoUsuario',
            field=models.TextField(default=1, verbose_name=200),
            preserve_default=False,
        ),
    ]
