# Generated by Django 4.0.3 on 2022-04-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_grupousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='GrupoUsuario',
            field=models.TextField(blank=True),
        ),
    ]
