# Generated by Django 4.0.3 on 2022-06-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_nomeusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bairro',
            field=models.TextField(blank=True),
        ),
    ]
