# Generated by Django 4.0.3 on 2022-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
