# Generated by Django 4.0.3 on 2022-04-18 01:00

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteCasamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capa', models.ImageField(upload_to='uploads/')),
                ('NomeNoivos', models.TextField(verbose_name=builtins.max)),
                ('Descricao', models.TextField(verbose_name=400)),
                ('Onde', models.TextField(verbose_name=builtins.max)),
                ('ListaPresentes', models.TextField(verbose_name=builtins.max)),
            ],
        ),
    ]
