# Generated by Django 4.0.3 on 2022-06-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidados',
            name='Acompanhantes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='convidados',
            name='NomeConvidado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='convidados',
            name='Observacoes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='convidados',
            name='TelefoneConvidado',
            field=models.CharField(max_length=100),
        ),
    ]
