# Generated by Django 4.0.3 on 2022-04-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConviteCasamento',
        ),
    ]
