# Generated by Django 4.0.3 on 2022-06-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convite', '0002_delete_convitecasamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteCasamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeNoiva', models.CharField(max_length=100)),
                ('NomeNoivo', models.CharField(max_length=100)),
                ('DataCasamento', models.DateTimeField()),
                ('Capa', models.ImageField(upload_to='')),
                ('FotoCasal', models.IntegerField()),
                ('Descricao', models.CharField(max_length=100)),
                ('Endereco', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Cep', models.CharField(max_length=100)),
                ('ListaPresentes', models.CharField(max_length=100)),
            ],
        ),
    ]
