# Generated by Django 4.0.3 on 2022-06-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convitecasamento',
            name='FotoCasal',
            field=models.ImageField(upload_to=''),
        ),
    ]
